DROP TABLE IF EXISTS players;
CREATE TABLE players(Id INTEGER PRIMARY KEY, Name TEXT);
DROP TABLE IF EXISTS matches;
CREATE TABLE matches(Id INTEGER PRIMARY KEY, MatchId INTEGER, PlayerId INTEGER, Score INTEGER);
